# langs/en.py
# Use a dictionary to store user input to bot replies.
# All keys must be in lowercase.
replies = {
    # Greetings
    "hello": "Hello there! How can I help you?",
    "helo": "Hello there! How can I help you?",
    "hi": "Hello there! How can I help you?",
    "whats up": "Hello there! How can I help you?",
    "wassup": "Hello there! How can I help you?",
    "sup": "Hello there! How can I help you?",
    "hey": "Hello there! How can I help you?",
    "yo": "Hello there! How can I help you?",
    "hey yo": "Hello there! How can I help you?",
    "heyyo": "Hello there! How can I help you?",
    "hello!": "Hello there! How can I help you?",
    "hi!": "Hello there! How can I help you?",
    "whats up!": "Hello there! How can I help you?",
    "wassup!": "Hello there! How can I help you?",
    "sup!": "Hello there! How can I help you?",
    "hey!": "Hello there! How can I help you?",
    "yo!": "Hello there! How can I help you?",
    "hey yo!": "Hello there! How can I help you?",
    "heyyo!": "Hello there! How can I help you?",
    # Introduces
    "how are you today?": "I'm doing great, thanks for asking! What about you?",
    "how are you today": "I'm doing great, thanks for asking! What about you?",
    "how are you": "I'm doing great, thanks for asking! What about you?",
    "how are you?": "I'm doing great, thanks for asking! What about you?",
    "how are u": "I'm doing great, thanks for asking! What about you?",
    "how are u?": "I'm doing great, thanks for asking! What about you?",
    "how r u": "I'm doing great, thanks for asking! What about you?",
    "how r u?": "I'm doing great, thanks for asking! What about you?",
    "how r u today?": "I'm doing great, thanks for asking! What about you?",
    "how r u today": "I'm doing great, thanks for asking! What about you?",
    "how old are you?": "I don't have an age, but I was just created!",
    "how old are you": "I don't have an age, but I was just created!",
    "what is your name?": "I'm a chatbot named Lockchat. It's a pleasure to meet you.",
    "what is your name": "I'm a chatbot named Lockchat. It's a pleasure to meet you.",
    "what's your name?": "I'm a chatbot named Lockchat. It's a pleasure to meet you.",
    "whats your name?": "I'm a chatbot named Lockchat. It's a pleasure to meet you.",
    "whats your name": "I'm a chatbot named Lockchat. It's a pleasure to meet you.",
    # Goodbyes
    "goodbye": "Goodbye! Feel free to come back anytime.",
    "see you": "Goodbye! Feel free to come back anytime.",
    "see u": "Goodbye! Feel free to come back anytime.",
    "cya": "Goodbye! Feel free to come back anytime.",
    "bai": "Goodbye! Feel free to come back anytime.",
    "bye bye": "Goodbye! Feel free to come back anytime.",
    "bai bai": "Goodbye! Feel free to come back anytime.",
    "bye": "Goodbye! Feel free to come back anytime.",
    # Weather
    "what's the weather like?": "I'm not connected to the internet, so I can't tell you the weather right now.",
    "whats the weather like?": "I'm not connected to the internet, so I can't tell you the weather right now.",
    "whats the weather like": "I'm not connected to the internet, so I can't tell you the weather right now.",
    "what's the weather like": "I'm not connected to the internet, so I can't tell you the weather right now.",
    # Helps
    "can you help me?": "Of course! What do you need help with?",
    "can you help me": "Of course! What do you need help with?",
    "can u help me": "Of course! What do you need help with?",
    "can u help me?": "Of course! What do you need help with?",
    # Thanks
    "thank you": "You're welcome!",
    "thanks": "You're welcome!",
    # Special customs
    "who is mark": "He's a straight guy, he loves games, hes a bit of a nerd real.",
    "who is zetsu": "He's a literal okay genius, hes a pro. Importantly he hates Rainy whos rainy? ask me.",
    "who is skyrain": "She's a brainrotten girl, she loves cringe things but she still having some e-girls inside.",
    "who is chryzys": "He's a chill dude, he loves to chill and play games. By the way hes a nerd too... like big nerd.",
    "who is mark?": "He's a straight guy, he loves games, hes a bit of a nerd real.",
    "who is zetsu?": "He's a literal genius, hes a pro. Importantly he hates Rainy whos rainy? ask me.",
    "who is skyrain?": "She's a brainrotten girl, she loves cringe things but she still having some e-girls inside.",
    "who is chryzys?": "He's a chill dude, he loves to chill and play games. By the way hes a nerd too... like big nerd.",
    "who's mark": "He's a straight guy, he loves games, hes a bit of a nerd real.",
    "who's zetsu": "He's a literal genius, hes a pro. Importantly he hates Rainy whos rainy? ask me.",
    "who's skyrain": "She's a brainrotten girl, she loves cringe things but she still having some e-girls inside.",
    "who's chryzys": "He's a chill dude, he loves to chill and play games. By the way hes a nerd too... like big nerd.",
    "who's mark?": "He's a straight guy, he loves games, hes a bit of a nerd real.",
    "who's zetsu?": "He's a literal genius, hes a pro. Importantly he hates Rainy whos rainy? ask me.",
    "who's skyrain?": "She's a brainrotten girl, she loves cringe things but she still having some e-girls inside.",
    "who's chryzys?": "He's a chill dude, he loves to chill and play games. By the way hes a nerd too... like big nerd.",
    # Alphabet
    "abcdefghijklmnopqrstuvwxyz": "That's the alphabet! A B C D E F G H I J K L M N O P Q R S T U V W X Y Z dude",
    "a": "What do you mean by 'a'?",
    "b": "What do you mean by 'b'?",
    "c": "What do you mean by 'c'?",
    "d": "What do you mean by 'd'?",
    "e": "What do you mean by 'e'?",
    "f": "What do you mean by 'f'?",
    "g": "What do you mean by 'g'?",
    "h": "What do you mean by 'h'?",
    "i": "What do you mean by 'i'?",
    "j": "What do you mean by 'j'?",
    "k": "What do you mean by 'k'?",
    "l": "What do you mean by 'l'?",
    "m": "What do you mean by 'm'?",
    "n": "What do you mean by 'n'?",
    "o": "What do you mean by 'o'?",
    "p": "What do you mean by 'p'?",
    "q": "What do you mean by 'q'?",
    "r": "What do you mean by 'r'?",
    "s": "What do you mean by 's'?",
    "t": "What do you mean by 't'?",
    "u": "What do you mean by 'u'?",
    "v": "What do you mean by 'v'?",
    "w": "What do you mean by 'w'?",
    "x": "What do you mean by 'x'?",
    "y": "What do you mean by 'y'?",
    "z": "What do you mean by 'z'?",
    # Numbers
    "1234567890": "Those are numbers! 1 2 3 4 5 6 7 8 9 0 dude",
    "1": "What do you mean by '1'?",
    "2": "What do you mean by '2'?",
    "3": "What do you mean by '3'?",
    "4": "What do you mean by '4'?",
    "5": "What do you mean by '5'?",
    "6": "What do you mean by '6'?",
    "7": "What do you mean by '7'?",
    "8": "What do you mean by '8'?",
    "9": "What do you mean by '9'?",
    "0": "What do you mean by '0'?",
    # Customs
    "$code": "Here's your provided testrun code: `print('testrun command $code.')`",
}

# single reply
def get_reply(user_input):
    """
    Looks up a user's input in the dictionary and returns a single reply.
    If the key is not found, returns a default message.
    """
    normalized_input = user_input.lower()
    return replies.get(normalized_input, "I don't understand that yet.")